services:
  anonymous:
    path: anonymous
    params:
      rootDomain: colanderapp.io
      jwtSigningSecret: shhh

  websocket:
    path: websocket
    params:
      rootDomain: colanderapp.io
      jwtSigningSecret: shhh

  event:
    path: event
    params:
      websocketApiId: ${websocket.appWebsocketApiId}

  organization:
    path: organization
    params:
      websocketApiId: ${websocket.appWebsocketApiId}
